Fix move the cursor to the point, not the line
blue0513/point-history pull request #16
Opened 2019-04-26 06:06 UTC by SuzumiyaAoba

Hi!

This package moves the cursor to the line from the history.
Is this the specification which you hoped for?

I think it is better that the cursor is moved to the point, not the line.
Please consider my proposal :smile: 

P.S. Maybe you can try making an option of choosing a point or a line.

2019-04-26 10:08 UTC, SuzumiyaAoba commented
This change is related to 1dc4b20.

2019-04-26 14:10 UTC, blue0513 commented
@SuzumiyaAoba Thx for the proposal!  
Yeah, as you said, moving to the point is better for users. 

I'll review your PR then should merge!

2019-04-26 14:15 UTC, blue0513 commented on point-history.el
> +    (goto-char pos)
nice :+1:

2019-04-26 14:25 UTC, blue0513 requested changes
Plz consider these points:  
1. When you close `point-history-show-buffer` by [`point-history-close`](https://github.com/blue0513/point-history/blob/master/point-history.el#L102-L105), it should call `goto-char`
2. To realize it, you should modify `point-history-last-visited-buffer` to contains `position` instead of `line-number` on [these lines](https://github.com/blue0513/point-history/blob/master/point-history.el#L191-L192)

2019-05-05 07:43 UTC, blue0513 approved these changes

2019-05-05 07:47 UTC, blue0513 commented
@SuzumiyaAoba LGTM! :+1:
But before merge this PR, you should squash these two commits to one. After that, I'll merge it

2019-05-05 11:04 UTC, merged

2019-05-05 11:05 UTC, blue0513 commented
@SuzumiyaAoba Thx! Merged!